/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SampleService } from "../sample.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SampleCreateInput } from "./SampleCreateInput";
import { Sample } from "./Sample";
import { SampleFindManyArgs } from "./SampleFindManyArgs";
import { SampleWhereUniqueInput } from "./SampleWhereUniqueInput";
import { SampleUpdateInput } from "./SampleUpdateInput";
import { ExpressionDataFindManyArgs } from "../../expressionData/base/ExpressionDataFindManyArgs";
import { ExpressionData } from "../../expressionData/base/ExpressionData";
import { ExpressionDataWhereUniqueInput } from "../../expressionData/base/ExpressionDataWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SampleControllerBase {
  constructor(
    protected readonly service: SampleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sample })
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSample(@common.Body() data: SampleCreateInput): Promise<Sample> {
    return await this.service.createSample({
      data: data,
      select: {
        collectionDate: true,
        createdAt: true,
        description: true,
        id: true,
        sampleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Sample] })
  @ApiNestedQuery(SampleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async samples(@common.Req() request: Request): Promise<Sample[]> {
    const args = plainToClass(SampleFindManyArgs, request.query);
    return this.service.samples({
      ...args,
      select: {
        collectionDate: true,
        createdAt: true,
        description: true,
        id: true,
        sampleName: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sample })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sample(
    @common.Param() params: SampleWhereUniqueInput
  ): Promise<Sample | null> {
    const result = await this.service.sample({
      where: params,
      select: {
        collectionDate: true,
        createdAt: true,
        description: true,
        id: true,
        sampleName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sample })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSample(
    @common.Param() params: SampleWhereUniqueInput,
    @common.Body() data: SampleUpdateInput
  ): Promise<Sample | null> {
    try {
      return await this.service.updateSample({
        where: params,
        data: data,
        select: {
          collectionDate: true,
          createdAt: true,
          description: true,
          id: true,
          sampleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sample })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSample(
    @common.Param() params: SampleWhereUniqueInput
  ): Promise<Sample | null> {
    try {
      return await this.service.deleteSample({
        where: params,
        select: {
          collectionDate: true,
          createdAt: true,
          description: true,
          id: true,
          sampleName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/expressionDataItems")
  @ApiNestedQuery(ExpressionDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "read",
    possession: "any",
  })
  async findExpressionDataItems(
    @common.Req() request: Request,
    @common.Param() params: SampleWhereUniqueInput
  ): Promise<ExpressionData[]> {
    const query = plainToClass(ExpressionDataFindManyArgs, request.query);
    const results = await this.service.findExpressionDataItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        expressionValue: true,

        gene: {
          select: {
            id: true,
          },
        },

        id: true,

        sample: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/expressionDataItems")
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "update",
    possession: "any",
  })
  async connectExpressionDataItems(
    @common.Param() params: SampleWhereUniqueInput,
    @common.Body() body: ExpressionDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expressionDataItems: {
        connect: body,
      },
    };
    await this.service.updateSample({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/expressionDataItems")
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "update",
    possession: "any",
  })
  async updateExpressionDataItems(
    @common.Param() params: SampleWhereUniqueInput,
    @common.Body() body: ExpressionDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expressionDataItems: {
        set: body,
      },
    };
    await this.service.updateSample({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/expressionDataItems")
  @nestAccessControl.UseRoles({
    resource: "Sample",
    action: "update",
    possession: "any",
  })
  async disconnectExpressionDataItems(
    @common.Param() params: SampleWhereUniqueInput,
    @common.Body() body: ExpressionDataWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      expressionDataItems: {
        disconnect: body,
      },
    };
    await this.service.updateSample({
      where: params,
      data,
      select: { id: true },
    });
  }
}
