/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExpressionDataService } from "../expressionData.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpressionDataCreateInput } from "./ExpressionDataCreateInput";
import { ExpressionData } from "./ExpressionData";
import { ExpressionDataFindManyArgs } from "./ExpressionDataFindManyArgs";
import { ExpressionDataWhereUniqueInput } from "./ExpressionDataWhereUniqueInput";
import { ExpressionDataUpdateInput } from "./ExpressionDataUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExpressionDataControllerBase {
  constructor(
    protected readonly service: ExpressionDataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExpressionData })
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExpressionData(
    @common.Body() data: ExpressionDataCreateInput
  ): Promise<ExpressionData> {
    return await this.service.createExpressionData({
      data: {
        ...data,

        gene: data.gene
          ? {
              connect: data.gene,
            }
          : undefined,

        sample: data.sample
          ? {
              connect: data.sample,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expressionValue: true,

        gene: {
          select: {
            id: true,
          },
        },

        id: true,

        sample: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExpressionData] })
  @ApiNestedQuery(ExpressionDataFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expressionDataItems(
    @common.Req() request: Request
  ): Promise<ExpressionData[]> {
    const args = plainToClass(ExpressionDataFindManyArgs, request.query);
    return this.service.expressionDataItems({
      ...args,
      select: {
        createdAt: true,
        expressionValue: true,

        gene: {
          select: {
            id: true,
          },
        },

        id: true,

        sample: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExpressionData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expressionData(
    @common.Param() params: ExpressionDataWhereUniqueInput
  ): Promise<ExpressionData | null> {
    const result = await this.service.expressionData({
      where: params,
      select: {
        createdAt: true,
        expressionValue: true,

        gene: {
          select: {
            id: true,
          },
        },

        id: true,

        sample: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExpressionData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExpressionData(
    @common.Param() params: ExpressionDataWhereUniqueInput,
    @common.Body() data: ExpressionDataUpdateInput
  ): Promise<ExpressionData | null> {
    try {
      return await this.service.updateExpressionData({
        where: params,
        data: {
          ...data,

          gene: data.gene
            ? {
                connect: data.gene,
              }
            : undefined,

          sample: data.sample
            ? {
                connect: data.sample,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expressionValue: true,

          gene: {
            select: {
              id: true,
            },
          },

          id: true,

          sample: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExpressionData })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpressionData",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExpressionData(
    @common.Param() params: ExpressionDataWhereUniqueInput
  ): Promise<ExpressionData | null> {
    try {
      return await this.service.deleteExpressionData({
        where: params,
        select: {
          createdAt: true,
          expressionValue: true,

          gene: {
            select: {
              id: true,
            },
          },

          id: true,

          sample: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
